---

- name: Install Dell DSU repo
  environment: "{{proxy_env|default({})}}"
  shell: "wget -q -O - http://linux.dell.com/repo/hardware/dsu/bootstrap.cgi | bash"
  args:
     creates: /etc/yum.repos.d/dell-system-update
  tags: skip_ansible_lint
  register: reg_install_dsu_repo
  when: dell_dsu_repo_install
  failed_when: "'Done!' not in reg_install_dsu_repo.stdout"

- name: Install Dell DSU prerequisites
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - usbutils
    - compat-libstdc++-33.i686
    - OpenIPMI

- name: Installing Dell DSU RPM
  yum:
    name: dell-system-update
    state: present

- name: Update firmware
  command: "dsu -n"
  when: dell_dsu_update_all_firmware
