---

- name: Make sure this is only run on a dell server
  assert:
    that: ansible_system_vendor is match('Dell.*')
    msg: "This role is only meant to be run on Dell systems"
  when: dell_dsu_assert

- name: include multipathd.yml if dell_dsu_manage_multipath_config is True
  include_tasks: multipathd.yml
  when: dell_dsu_manage_multipath_config

- name: Install Dell DSU repo
  environment: "{{proxy_env|default({})}}"
  shell: "wget -q -O - http://linux.dell.com/repo/hardware/dsu/bootstrap.cgi | bash"
  args:
     creates: /etc/yum.repos.d/dell-system-update.repo
  tags: skip_ansible_lint
  register: reg_install_dsu_repo
  when: dell_dsu_repo_install
  failed_when: "('Done!' not in reg_install_dsu_repo.stdout) and (reg_install_dsu_repo.rc != 0)"

- name: print reg_install_dsu_repo variable if verbosity is 1
  debug:
    var: reg_install_dsu_repo
    verbosity: 1

- name: Install Dell DSU prerequisites
  yum:
    name: "{{ dell_dsu_prerequisites }}"
    state: present

- name: Installing Dell DSU RPM
  yum:
    name: dell-system-update
    state: present

- name: Update firmware
  command: "dsu {{ dell_dsu_arguments }}"
  when: dell_dsu_update_all_firmware
  register: command_result
  failed_when: command_result.rc not in dell_dsu_changed_exit_codes + dell_dsu_not_changed_exit_codes
  changed_when: command_result.rc in dell_dsu_changed_exit_codes
