---

- name: Check /etc/multipath.conf
  stat:
    path: /etc/multipath.conf
  register: stat_multipath_conf

- name: Check service multipathd
  service:
    name: multipathd
  register: service_multipathd

- name: Add blacklist to multipath.conf
  blockinfile:
    block: |
      blacklist {
              devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
              devnode "^hd[a-z]*"
              devnode "^cciss!c[0-9]d[0-9]*[p[0-9]*]"
              devnode "^asm/*"
              devnode "ofsctl"

              device {
                      vendor "DELL"
                      product "IDSDM"
              }
              device {
                      vendor "iDRAC"
                      product "MAS022"
              }
              device {
                      vendor "iDRAC"
                      product "SECUPD"
              }
              device {
                      vendor "iDRAC"
                      product "scrtch"
              }
      }
    backup: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK Dell DSU Blacklist"
    path: /etc/multipath.conf
    state: present
  register: blockinfile_multipath_config
  when:
    - stat_multipath_conf.stat.exists is defined and stat_multipath_conf.stat.exists
    - service_multipathd.status.ActiveState == "active"

- name: reload multipathd
  service:
    name: multipathd
    state: reloaded
  when:
    - blockinfile_multipath_config.changed
